name: Publish

on:
  push:
    branches:
      - main

# recommended: reset permissions and explicitly specify for each job
permissions: {}

# recommended: avoid concurrent runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  select-mode:
    runs-on: ubuntu-latest
    outputs:
      mode: ${{ steps.select-mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.select-mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read # to check out repo (actions/checkout)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false # recommended: do not persist git credentials on disk

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Select Changesets mode
        id: select-mode
        uses: changesets/action/select-mode@v2

  version:
    if: needs.select-mode.outputs.mode == 'version'
    needs: select-mode
    runs-on: ubuntu-latest
    outputs:
      version-dir-artifact-id: ${{ steps.version.outputs.version-dir-artifact-id }}
    permissions:
      contents: write # to check out repo (actions/checkout) and commit version changes (changesets/action/version)
      pull-requests: write # to create pull request (changesets/action/version)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false # recommended: do not persist git credentials on disk

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # recommended: avoid cache poisoning

      - name: Install dependencies
        run: npm install

      - name: Version packages
        id: version
        uses: changesets/action/version@v2

  pack:
    if: needs.select-mode.outputs.mode == 'publish'
    needs: select-mode
    runs-on: ubuntu-latest
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read # to check out repo (actions/checkout)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false # recommended: do not persist git credentials on disk

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # recommended: avoid cache poisoning

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm build

      - name: Pack packages
        id: pack
        uses: changesets/action/pack@v2
        with:
          publish-plan-artifact-id: ${{ needs.select-mode.outputs.publish-plan-artifact-id }}

  publish:
    needs: pack
    runs-on: ubuntu-latest
    permissions:
      contents: write # to check out repo (actions/checkout) and to create releases (changesets/action/publish)
      id-token: write # for trusted publishing (changesets/action/publish)
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false # recommended: do not persist git credentials on disk

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false # recommended: avoid cache poisoning

      - name: Install dependencies
        run: npm install

      - name: Publish packages
        uses: changesets/action/publish@v2
        with:
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
