# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Packages in packages/
  - package-ecosystem: "npm"
    directory: "/packages/apply-release-plan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/assemble-release-plan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/changelog-git"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/changelog-github"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/cli/changelog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/cli/commit"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/config"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/errors"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/get-dependents-graph"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/get-github-info"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/get-release-plan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/get-version-range-type"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/logger"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/parse"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/pre"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/read"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/release-utils"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/should-skip-package"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/types"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/write"
    schedule:
      interval: "weekly"

  # scripts folder packages
  - package-ecosystem: "npm"
    directory: "/scripts/test-utils"
    schedule:
      interval: "weekly"

  # GitHub Actions updates for workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

