packages:
  - packages/*
  - scripts/*

allowBuilds:
  "@pnpm/pnpr": true
  bun: true
blockExoticSubdeps: true
dedupePeers: true
dedupePeerDependents: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@changesets/format@0.1.1"
  - pnpm@11.13.1
  - npm@12.0.1
  - pnpm@10.34.5
overrides:
  rolldown: 1.0.3
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - pnpm@10.34.5
