name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - next
  merge_group:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  test:
    name: "Test using Node ${{ matrix.node_version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        node_version: [22, 24, 26]
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup
        with:
          node-version: ${{ matrix.node_version }}

      - name: Check Git version
        run: git --version

      - name: Setup mock Git user
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: Vitest tests
        if: matrix.node_version != 24
        run: node --run test

      # Run coverage only once on node 24 to avoid duplicate codecov uploads
      - name: Vitest tests with coverage
        if: matrix.node_version == 24
        run: node --run test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: matrix.node_version == 24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup

      - name: Typecheck
        run: node --run types:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup

      - name: Lint
        run: node --run lint

      - name: Format
        run: node --run format

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs: [test, typecheck, lint]
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
