name: pkg-pr-new

on:
  pull_request:
    types: [labeled]
  # publish each commit to main/next
  #push:
    #branches: ["main", "next"]
    #tags: ["!**"]

permissions: {}

jobs:
  publish:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'pkg.pr.new') }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup
        with:
          node-version: 26

      - name: Build
        run: pnpm build

      - run: pnpm exec pkg-pr-new publish --pnpm --packageManager=pnpm --commentWithDev --commentWithSha './packages/*'
