name: Publish

on:
  push:
    branches:
      - main
      - next
      - "maintenance/v*" # branch rulesets don't support v[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  queue: max

permissions: {} # each job should define its own permission explicitly

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    environment: version
    timeout-minutes: 20
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    permissions:
      contents: read # to check out repo (actions/checkout)
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup
        with:
          skip-cache: true # avoid cache poisoning attacks

      - name: Build artifacts
        run: pnpm build

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # to create version commits (changesets/action)
          permission-pull-requests: write # to create pull request (changesets/action)

      - name: Create or update release pull request
        id: changesets
        # https://github.com/changesets/action
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          version: pnpm version-packages

  publish:
    name: Publish
    if: needs.version.outputs.hasChangesets == 'false'
    needs: version
    runs-on: ubuntu-latest
    environment: npm
    timeout-minutes: 20
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # to use OpenID Connect token for trusted publishing (changesets/action)
    steps:
      - name: Check out repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/ci-setup
        with:
          node-version: 24
          skip-cache: true # avoid cache poisoning attacks

      - name: Build artifacts
        run: pnpm build

      - name: Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
